[package]
name = "ws-types"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1.1"
chrono = { version = "0.4", features = [ "serde" ] }
rand = "0.8.5"